### ISSUE TITLE
X.3 & X4 in mac OSX.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [djsmisc/pinguino32#36]
```
Hi all .. I am again with pinguino....

What steps will reproduce the problem?
1. Try to run GUI  
2. With Python Version 2.7.3
3. With wx version 2.9.4

What is the expected output? What do you see instead?
RUN GUI...

What version of the product are you using? On what operating system?
X.3 & X.4 error from the PYTHON command line

Please provide any additional information below.
X.3
HP-walii-MAC-OSX:x.3 walterleonardo$ python pinguino.py 
pinguino.py:79: wxPyDeprecationWarning: Using deprecated class PySimpleApp. 
  app = wx.PySimpleApp(0)
Traceback (most recent call last):
  File "pinguino.py", line 151, in <module>
    main()
  File "pinguino.py", line 68, in main
    app = MyApp(False)
  File "/usr/local/lib/wxPython-2.9.4.0/lib/python2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 8631, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/wxPython-2.9.4.0/lib/python2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "pinguino.py", line 56, in OnInit
    frame.__initPinguino__(None)
  File "/Users/walterleonardo/Pinguino/pinguino32-read-only/x.3/wxgui/pinguino.py", line 126, in __initPinguino__
    self.buildEditor()
  File "/Users/walterleonardo/Pinguino/pinguino32-read-only/x.3/wxgui/pinguino.py", line 195, in buildEditor
    self.lat = panelLateral(self)
  File "/Users/walterleonardo/Pinguino/pinguino32-read-only/x.3/wxgui/frames/framesX3.py", line 877, in __init__
    fgSizer1.AddSpacer( ( 0, 0), 1, wx.EXPAND, 5 )
  File "/usr/local/lib/wxPython-2.9.4.0/lib/python2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 14688, in AddSpacer
    return self.Add(*args, **kw)
  File "/usr/local/lib/wxPython-2.9.4.0/lib/python2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 14469, in Add
    return _core_.Sizer_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at 
/BUILD/wxPython-src-2.9.4.0/src/common/sizer.cpp(1377) in DoInsert(): too many 
items (5 > 2*2) in grid sizer (maybe you should omit the number of either rows 
or columns?)



X.4
sh-3.2# python pinguino.py 
Traceback (most recent call last):
  File "pinguino.py", line 6, in <module>
    from wxgui.pinguino import setGui
  File "/Users/walterleonardo/Pinguino/x.4/wxgui/__init__.py", line 4, in <module>
    from framesX3 import framePinguinoX, frameKeyWords, framePreferences, panelLateral, menubarPinguino, frameAutoCompleter, panelOutput
  File "/Users/walterleonardo/Pinguino/x.4/wxgui/framesX3.py", line 14, in <module>
    import gettext
  File "/Users/walterleonardo/Pinguino/x.4/wxgui/gettext.py", line 7, in <module>
    from wxgui._trad import _ as gettext
  File "/Users/walterleonardo/Pinguino/x.4/wxgui/_trad.py", line 37, in <module>
    lang = gettext.translation('pinguino', os.path.join(sys.path[0], 'locale'), languages=[loc], fallback=True)
AttributeError: 'module' object has no attribute 'translation'

```

Original issue reported on code.google.com by `walterleonardo@gmail.com` on 9 Jan 2013 at 11:29

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue. It doesn't work in wxwidget version 2.9.3.1 either.

I tried to fix the problem through fixing the framesX4.py / framesX3.py files. 
I changed the following line:

fgSizer1 = wx.FlexGridSizer( 2, 2, 0, 0 )

to:

fgSizer1 = wx.FlexGridSizer( 0, 0, 0, 0)

This way, the program starts up. But as soon as I make any actions, for example 
changing the board type, the program crashes.

Any ideas anyone ....

Regrads Dirk


```

Original comment by `dirkpors...@googlemail.com` on 3 Feb 2013 at 7:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `rblanchot@gmail.com` on 23 Apr 2013 at 9:59
- Changed state: **Fixed**
